/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvmapp_Demo */

#ifndef _Included_jvmapp_Demo
#define _Included_jvmapp_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvmapp_Demo
 * Method:    testReentrant
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jvmapp_Demo_testReentrant
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
