#pragma once

#include <GLES3/gl3.h>

namespace graphics {
    enum class blend_function : GLenum {
        ZERO = GL_ZERO,
        ONE = GL_ONE,
        ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR,
        SRC_COLOR = GL_SRC_COLOR,
        ONE_MINUS_DST_COLOR = GL_ONE_MINUS_DST_COLOR,
        DST_COLOR = GL_DST_COLOR,
        ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
        SRC_ALPHA = GL_SRC_ALPHA,
        ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA,
        DST_ALPHA = GL_DST_ALPHA,
        ONE_MINUS_CONSTANT_COLOR = GL_ONE_MINUS_CONSTANT_COLOR,
        CONSTANT_COLOR = GL_CONSTANT_COLOR,
        ONE_MINUS_CONSTANT_ALPHA = GL_ONE_MINUS_CONSTANT_ALPHA,
        CONSTANT_ALPHA = GL_CONSTANT_ALPHA,
        SRC_ALPHA_SATURATE = GL_SRC_ALPHA_SATURATE
    };
}